name: tech_control
description: "Tech control"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.2
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  go_router: ^13.0.0
  floor: ^1.4.2
  connectivity: ^3.0.6
  analyzer: ^5.0.0
  qr_code_scanner: ^1.0.1
  flutter_easyloading: ^3.0.5
  device_apps: ^2.2.0
  android_intent_plus: ^5.0.1
  url_launcher: ^6.2.5
  external_app_launcher: ^3.0.0
  share_plus: ^8.0.2


dev_dependencies:
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  flutter_assets_generator: any
  flutter_gen: any

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_logo.png'
  min_sdk_android: 21
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lang/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
          weight: 400  # FontWeight.w400 is used for bold
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 700  # FontWeight.w700 is used for bold
        - asset: assets/fonts/montserrat_semi_bold.ttf
          weight: 600  # FontWeight.w600 is used for semi-bold
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 500  # FontWeight.w500 is used for medium
        - asset: assets/fonts/montserrat_extra_bold.ttf
          weight: 800  # FontWeight.w800 is used for extra-bold
